name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

env:
  ZMK_EXTRA_MODULES: "/github/workspace/boards"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
